danielSismer/ProjetoWEG_ONE

- ProjectJava.java
> feat: Texto inicial 'Bemvindo'

- ProjectJava.java
- messages_de.properties
- messages_en.properties
- messages_pt.properties
Eu criei uma API de tradução com recursos do Java.
> feat: Implementando a API de tradução

- ProjectJava.java
- messages_de.properties
- messages_en.properties
- messages_pt.properties
Adicionei os vetores para armazenar as orientações em todas as línguas, também adicionei os menus traduzidos.
> PJ-12: feat: Adicionando os vetores das orientações

- Epis.java
- MotoresPortao.java
- ProcedimentoOperacionalGeradores.java
- ProcedimentoOperacionalManutencao.java
- ProcedimentoOperacionalQualidade.java
- SeguracaEquipamentosEletricos.java
- SegurancaChoqueEletrico.java
- SegurancaDiagnostico.java
- Transformadores.java
- segurancaTesteMotor.java
Essa branch tem como objetivo a criação de classes auxiliares para representar objetos específicos do sistema. A mudança visa reduzir a complexidade e o tamanho da classe principal, melhorando a organização e a manutenção do código
> PJ-20 Feat/finalizando classes

- OpcoesDoMenu.java
- Tela_inicial.java
Nesse código não foi adicionada nenhuma melhora , na verdade foi reformado com métodos e objetos já que o código estava difícil de entender.
> PJ-29  Feat/tela menu, Reformas 

- OpcoesDoMenu.java
- Tela_inicial.java
Adicionei os botões de "Ir" e "Voltar" para facilitar a navegação entre as janelas do sistema, incluí um cabeçalho nas novas janelas para manter a consistência visual da interface e corrigi a imagem principal, ajustando seu posicionamento e aparência para melhor apresentação.
> PJ-29 feat/ Inserir botão de voltar

- ProjectJava.java
Renomeei o nome de alguns objetos, pois havia uma ambiguidade e poderia causar futuros conflitos
> Fix: PJ-37 Renomeando objetos de classes

- ProjectJava.java
- messages_pt.properties
Essa codigo ira finalizar e ajustar corretamente toda a parte de estrutura e de set da criação das classes
> feat criando chave para as orientações visando automatizar o codigo

- messages_de.properties
- messages_en.properties
- messages_pt.properties
Criei chaves para cada uma das orientações e menus.
> Feat/traducao PJ-34 Finalizei os textos das propriedades.

- ProjectJava.java
Realizei a feat de editar orientação, seja qualquer valor dela. Foi um pouco trabalhosa pois precisava garantir que o valor que o usuario edite, seja o atual, e não outro.
> Feat: PJ-21 Implementei o uso de edição de orientações

- ProjectJava.java
- messages_de.properties
Ajuste nas properties ajustando cada lingua e ajustando para cada case
> PJ-39 Fix/Ajustando properties de linguagem alemã

- ProjectJava.java
- messages_de.properties
- messages_en.properties
- messages_pt.properties
Também fiz umas pequenas alterações em cada uma das properties, adiconando alguns "\n"
> PJ-37 Fiz os setters nos cases 1 e 2

- Index.java
- Index2.java
- LoginAdm.java
Criando a tela de login no java swing
> PJ-38:Feat/ Fazendo tela de Login

- ProjectJava.java
Arrumando um pequeno erro que estava acontecendo quanodo utilizava a função do cadastro
> feat: Arrumando pequeno erro que estava acontecendo no cadastro

- ProjectJava.java
> PJ-22 fix: Terminei de ajustar o sistema de exclusão

- ConexaoBanco.java
- LoginAdm.java
- TelaDeslogada.java
- TelaLogada.java
- TesteConexaoBanco.java
Fiz a conexão com o Banco de dados, utilizei o JDBC para fazer a conexão.
> Feat: Conectando Database com Java (Falta apenas ajustar a versão do Maven para funcionar 100%

- LoginAdm.java
- TelaDeslogada.java
- TesteConexaoBanco.java
- pom.xml
Fiz a implementação de autenticação de usuario com o Banco de Dados
> Feat PJ-43: Fiz a autenticação de usuario para fazer login, tela de login ja esta 100 funcional

- ProjectJava.java
> PJ-42: Terminei a estrutura inteira do código.

- .idea/workspace.xml
- src/main/java/net/weg/services/ManualCondutaSetorial.java
- src/main/java/net/weg/services/ManualDeOperacao.java
- src/main/java/net/weg/services/ManutencaoReparo.java
- src/main/java/net/weg/services/ProcedimentodeSeguranca.java
- src/main/java/net/weg/services/ProjectJava.java
- src/main/java/net/weg/services/TesteDiagnostico.java
Arrumando pequenos detalhes na classe de cadastro "feito por Kael problema no computador subiu em outra conta "
> fix arrumando e melhorando a utilização da funcionalidade de cadastro.

- src/main/java/net/weg/services/ProjectJava.java
- [✓] Arrumei o cadastro (agora não cadastra mais por cima das orientações anteriores)
Motivo do erro:
```java
if (itensManualDeOperacao[i] != null) {
```
O cadastro estava cadastrando apenas por cima de células que não eram nulas, sendo que deveria ser o contrário
```java
if (itensManualDeOperacao[i] == null) {
```
Esta é a forma correta.
- [✓] Arrumei a pesquisa (agora não fica mais retornando ao início quando tenta pesquisar)
Motivo do erro:
Anteriormente, não havia uma forma do código retornar para a pesquisa quando o usuário selecionasse para fazer mais pesquisas. A forma que eu utilizei para o código conseguir retornar para as pesquisas, caso fosse assim escolhido, foi:
```java
case 2{
do{
// Código
} while (continuarCadastro);
}
```
Um ‘do-while’ era necessário para que o sistema …
> PJ-81 e PJ-82: Testando, arrumando e adicionando funcionalidades no código.
